### ISSUE TITLE
_shared.js file and other files failed to load 

### ISSUE THREAD

**Issue by yehiaa** [sourcefabric/Newscoop#1048]
in dashboard page i got this error 
NetworkError: 404 Not Found - http://localhost:8080/admin/%5C/js/app/admin%5C_shared.js
in theme manager page /admin/themes
"NetworkError: 404 Not Found - http://localhost:8080/admin/%5C/js/app/admin%5Cthemes%5Cindex.js"
"NetworkError: 404 Not Found - http://localhost:8080/admin/%5C/js/app/admin%5C_shared.js"
"NetworkError: 404 Not Found - http://localhost:8080/admin/%5C/js/app/admin%5Cthemes%5Cindex.js"

%5C the code point for \
the problem in  "newscoop\library\Newscoop\Controller\Plugin\Js.php" i guess 
i use windows environment xampp . directory separator (\ in case of windows) can't be used in url 
thx

**Comment by ahilles107** [comment]
from what i know we don't support windows servers
