### ISSUE TITLE
JPEG compression

### ISSUE THREAD

**Issue by hudochenkov** [sourcefabric/Newscoop#1083]
Is it possible to change JPEG compression for generated images by tweaking some source file? Current JPEG quality isn't good enough.

**Comment by ahilles107** [comment]
hmm... can you tell more about those images? You talk about renditions, or images inside article body? We have few places where we work with images. Link for image would help

**Comment by hudochenkov** [comment]
I've look intently on the problem and it seems Newscoop have made big step in images quality from 3.* In 3.* resized images (`{{ url option="image 2 width 240" }}`) was not good looking enough.

Project I working on have source images poor quality so rendition resized images look bad also.

Can I tweak some phps to increase JPEG compression quality for renditions? Just in case I need it in future :)

**Comment by ahilles107** [comment]
Please check if your server have Image Magic installed - from our test we see that quality is much better on resize. And don't forget upgrade to 4.4.5 (486286c)
