### ISSUE TITLE
composer not working

### ISSUE THREAD

**Issue by JOduMonT** [sourcefabric/Newscoop#1388]
it must be : **curl -sS https://getcomposer.org/installer | sudo php**
instead of : _curl -s https://getcomposer.org/installer | php_ 

but even with that, i still have error with : php composer.phar install  --no-dev

> Composer successfully installed to: /var/www/composer.phar
> Use it: php composer.phar
> rescue@zopa:/var/www$ php composer.phar install --no-dev
> Composer could not find a composer.json file in /var/www
> To initialize a project, please create a composer.json file as described in the https:<//getcomposer.org/ "Getting Started" section

**Comment by takeit** [comment]
`curl -s https://getcomposer.org/installer | php` will also work.

The problem you are having is that you are installing Composer in wrong directory, it should be installed into Newscoop installation directory, for e.g. `/var/www/newscoop` (newscoop dir which keeps files from github repo) where the `composer.json` file is located.
