### ISSUE TITLE
Can we upgrade version 4.2.3 to 4.4.7?

### ISSUE THREAD

**Issue by arunkurusev** [sourcefabric/Newscoop#1396]

**Comment by takeit** [comment]
Hi @aruncse,

yes, please follow the below guides:
- [Upgrading Newscoop version 4.2.3/4.2.4/4.3.x to 4.3.x](https://github.com/sourcefabric/Newscoop/blob/v4.4/newscoop/docs/UPGRADE_4_3.md#upgrading-newscoop-version-42342443x-to-43x)
- [Upgrading Newscoop version 4.3.x/4.4.x to 4.4.x](https://github.com/sourcefabric/Newscoop/blob/v4.4/newscoop/docs/UPGRADE_4_4.md#upgrading-newscoop-version-43x44x-to-44x)
