### ISSUE TITLE
//install/license is 404 on remote server, works on localhost

### ISSUE THREAD

**Issue by d4goxn** [sourcefabric/Newscoop#1406]
When visiting the site, after running the composer install, everything looks good. However, the "next" link, to `//install/license` returns a 404 Not Found response.

![sys-compat](https://cloud.githubusercontent.com/assets/3030411/19629375/dd27a538-9928-11e6-9c98-578df1482e39.png)

I have ensured that permissions are correct for files and directories in the entire repo:

```
chown www-data:adm . -R
chmod g+rw . -R
find . -type d -exec chmod a+x {} +
```

This is with the Newscoop tagged release 4.4.7.

The strangest thing is, this works fine on localhost. It is only the remote server that this goes wrong. 

Everything is installed using Ansible, on an Ubuntu 16.04 server; if it helps, I have posted the playbook in a gist, at https://gist.github.com/d4goxn/9099d2b65b92136a387ab7ccf3e3fb46

**Comment by takeit** [comment]
Did you try to add `AllowOverride All` directive?

Example:

```
<VirtualHost *:80>
        <Directory /var/www/Newscoop/newscoop>
                AllowOverride All
        </Directory>
</VirtualHost>
```

**Comment by d4goxn** [comment]
That was it, thanks. I missed the entire `<Directory>` clause in the expert instructions.

http://sourcefabric.booktype.pro/newscoop-44-for-journalists-and-editors/expert-install/
