### ISSUE TITLE
Docker container really slow

### ISSUE THREAD

**Issue by vonhraban** [sourcefabric/Newscoop#1407]
My average page loading time is at least 8 seconds on a clean vanilla newscoop installation. I do not believe it is mySQL image causing the problem, instead it seems like mounted cache and log folder are the ones to blame. There are a lot read/writes happening from those files that are mounted, and this, I believe, slows down the whole thing.

**Comment by takeit** [comment]
Hi @vivecltd,

On Linux it used to work fine, we were using Newscoop with docker for development purposes. Are you maybe using OSX?

**Comment by vonhraban** [comment]
@takeit I have been running my docker natively in macOS, without boot2docker or docker toolbox. Could this be an issue?

**Comment by takeit** [comment]
Volumes on OSX are slow when using it with docker, check: https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/40

**Comment by vonhraban** [comment]
@takeit Ah I see, thank you. Never used docker natively on osX, so it is good to know
