### ISSUE TITLE
4.3.1 Backup/Restore does not work on Debian 7 Wheezy

### ISSUE THREAD

**Issue by graabein** [sourcefabric/Newscoop#942]
Hello.

I can not create backup in 4.3.1, and could not create backup in 4.2.4 either.  Now I have installation upgraded to 4.3.1 with help of Rafal in HipChat.  In other areas the installation works well, indicated by Rafal when helping me, and I have not discovered other errors...yet.

But Backup does not work.  In my initial 4.2.4 installation I followed installation guide here sourcefabric.booktype.pro/newscoop-43-for-journalists-and-editors/manual-installation/
I also did the recommended php.ini modifications.

I have tried both Backup from admin panel, and from command consol.

Both give this error message:
![backuperror](https://cloud.githubusercontent.com/assets/9559189/5803293/59ae0524-9ffd-11e4-8b83-0154a2e5c331.jpg)

**Comment by ahilles107** [comment]
it can be permissions issue, try to check apache error log for error message and give it for us here

**Comment by ahilles107** [comment]
ping...
